services:
  web-flask:
    image: python:3.11-slim  
    working_dir: /app
    volumes:
      - .:/app                
    ports:
      - "5001:5000"           
    environment:
      - FLASK_ENV=development 
    command: sh -c "pip install -r requirements.txt && python app.py"