spring:
  application:
    name: UserService

  datasource:
    url: jdbc:h2:mem:userservice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true

server:
  port: ${SERVER_PORT:8081}

app:
  jwt:
    secret: ${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw}
    expiration: ${JWT_EXPIRATION:86400000}
    issuer: UserService

logging:
  level:
    root: INFO
    fit.iuh.se.userservice: DEBUG

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://192.168.137.152:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 192.168.137.105
