# 1. Sử dụng nginx bản mới nhất
FROM nginx:latest

# 2. Copy file index.html vào thư mục mặc định của Nginx bên trong container
COPY index.html /usr/share/nginx/html/index.html

# 3. Nginx mặc định chạy cổng 80, nên ta EXPOSE để theo dõi
EXPOSE 80
