# Đặt mật khẩu truy cập cho Redis
requirepass iuh_secret_password

# Cho phép Redis chạy trên tất cả các interface
bind 0.0.0.0

# Giới hạn bộ nhớ tối đa (ví dụ 100MB cho nhẹ máy Mac)
maxmemory 100mb
maxmemory-policy allkeys-lru
